- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      pkg:
        - htop
        - zsh
        - tmux
        - rofi
        - cmus
        - samba
        - samba-common-bin
        - openssh-server
  - name: Make my user
    user:
      name: rohitt
      shell: /bin/zsh
      groups: sudo
      home: /home/rohitt
  # - name: Set hostname
  #   hostname:
  #     name: shoebox
  - name: Copy git config
    copy:
      src: files/.gitconfig
      dest: /home/rohitt/.gitconfig
      owner: rohitt
      group: sudo
      mode: 0644
