- hosts: all
  become: true
  tasks:
  - name: Install packages
    apt:
      pkg:
        - htop
        - zsh
        - tmux
        - rofi
        - cmus
        - samba
        - samba-common-bin

