- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      pkg:
        - htop
        - zsh
        - tmux
        - rofi
        - cmus
        - samba
        - samba-common-bin
        - openssh-server
  - name: Make my user
    user:
      name: rohitt
      shell: /bin/zsh
      groups: sudoers
      home: /home/rohitt
  - name: Set hostname
    hostname:
      name: shoebox
