- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - zsh
      - tmux
      - rofi
      - cmus
      - samba
      - samba-common-bin

